#!/usr/bin/env bash

paru -S dolphin hyprpaper hyprsunset hyprsysteminfo otf-font-awesome pavucontrol power-profiles-daemon qt6ct \
	ttf-font-awesome ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols waybar

# For waybar to work
if id -nG $USER | grep -qw input; then
    echo "User '$USER' is already in the 'input' group."
else
    echo "Adding '$USER' to 'input' group."

    sudo usermod -aG input $USER
fi
